sudo: required

services:
  - docker

language: generic

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

env:
  global:
    - DBVersion=9.6.1

script:
  ./Publish.sh
