sudo: required

services:
  - docker

language: generic

branches:
  only:
  - master

env:
  global:
    - DBVersion=9.6.1

script:
  - 'if [ "$TRAVIS_TAG" != "" ]; then
  ./Publish.sh $TRAVIS_TAG $DOCKER_USER $DOCKER_PASS $DBVersion
  fi'
