sudo: required

services:
  - docker

language: generic

branches:
  only:
  - master

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

deploy:
  provider: script
  script: ./Publish.sh
  on:
    tags: true
